//! Core MCP server implementation using rust-sdk

use crate::Config;
use rmcp::{
    handler::server::router::tool::ToolRouter, model::*, service::RequestContext, tool,
    tool_handler, tool_router, transport::stdio, Error as McpError, RoleServer, ServerHandler,
    ServiceExt,
};
use tracing::{debug, info};

/// The main CodePrism MCP Server implementation
#[derive(Clone)]
pub struct CodePrismMcpServer {
    /// Server configuration
    config: Config,
    /// Tool router for handling MCP tool calls
    tool_router: ToolRouter<CodePrismMcpServer>,
}

#[tool_router]
impl CodePrismMcpServer {
    /// Create a new MCP server instance
    pub async fn new(config: Config) -> std::result::Result<Self, crate::Error> {
        info!("Initializing CodePrism MCP Server");

        // Validate configuration
        config.validate()?;

        debug!("Server configuration validated successfully");

        Ok(Self {
            config,
            tool_router: Self::tool_router(),
        })
    }

    /// Simple ping tool for testing MCP functionality
    #[tool(description = "Simple ping tool that responds with pong")]
    fn ping(&self) -> std::result::Result<CallToolResult, McpError> {
        info!("Ping tool called");
        Ok(CallToolResult::success(vec![Content::text("pong")]))
    }

    /// Version tool that returns server version information
    #[tool(description = "Get server version and configuration information")]
    fn version(&self) -> std::result::Result<CallToolResult, McpError> {
        info!("Version tool called");

        let version_info = serde_json::json!({
            "server_name": self.config.server.name,
            "server_version": self.config.server.version,
            "mcp_protocol_version": crate::MCP_VERSION,
            "tools_enabled": {
                "core": self.config.tools.enable_core,
                "search": self.config.tools.enable_search,
                "analysis": self.config.tools.enable_analysis,
                "workflow": self.config.tools.enable_workflow
            }
        });

        Ok(CallToolResult::success(vec![Content::text(
            version_info.to_string(),
        )]))
    }

    /// Run the MCP server with stdio transport
    pub async fn run(self) -> std::result::Result<(), crate::Error> {
        info!(
            "Starting MCP server '{}' version {}",
            self.config.server.name, self.config.server.version
        );

        info!("Enabled tools:");
        info!("  Core tools: {}", self.config.tools.enable_core);
        info!("  Search tools: {}", self.config.tools.enable_search);
        info!("  Analysis tools: {}", self.config.tools.enable_analysis);
        info!("  Workflow tools: {}", self.config.tools.enable_workflow);

        info!("Starting MCP server with stdio transport");

        // Start the MCP server with stdio transport
        let service = self
            .serve(stdio())
            .await
            .map_err(|e| crate::Error::server_init(format!("Failed to start MCP server: {}", e)))?;

        info!("MCP server is ready to accept connections");

        // Wait for the server to complete
        service
            .waiting()
            .await
            .map_err(|e| crate::Error::server_init(format!("Server error: {}", e)))?;

        info!("MCP server shut down successfully");
        Ok(())
    }

    /// Get server configuration
    pub fn config(&self) -> &Config {
        &self.config
    }
}

#[tool_handler]
impl ServerHandler for CodePrismMcpServer {
    /// Provide server information and capabilities
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: self.config.server.name.clone(),
                version: self.config.server.version.clone(),
            },
            instructions: Some(
                "CodePrism MCP Server provides code analysis capabilities. \
                 Use the available tools to analyze code structure, search for patterns, \
                 and perform various code intelligence operations."
                    .to_string(),
            ),
        }
    }

    /// Initialize the server
    async fn initialize(
        &self,
        _request: InitializeRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> std::result::Result<InitializeResult, McpError> {
        info!("MCP server initialized successfully");
        Ok(self.get_info())
    }

    // Note: list_tools and call_tool are automatically generated by #[tool_handler] macro

    /// List resources (not implemented for now)
    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> std::result::Result<ListResourcesResult, McpError> {
        Ok(ListResourcesResult {
            resources: vec![],
            next_cursor: None,
        })
    }

    /// Read resource (not implemented for now)
    async fn read_resource(
        &self,
        _request: ReadResourceRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> std::result::Result<ReadResourceResult, McpError> {
        Err(McpError::invalid_params(
            "Resource reading not implemented",
            None,
        ))
    }

    /// List prompts (not implemented for now)
    async fn list_prompts(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> std::result::Result<ListPromptsResult, McpError> {
        Ok(ListPromptsResult {
            prompts: vec![],
            next_cursor: None,
        })
    }

    /// Get prompt (not implemented for now)
    async fn get_prompt(
        &self,
        _request: GetPromptRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> std::result::Result<GetPromptResult, McpError> {
        Err(McpError::invalid_params("Prompts not implemented", None))
    }

    /// List resource templates (not implemented for now)
    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> std::result::Result<ListResourceTemplatesResult, McpError> {
        Ok(ListResourceTemplatesResult {
            resource_templates: vec![],
            next_cursor: None,
        })
    }
}
