blank_issues_enabled: false
contact_links:
  - name: "🤖 AI Developer Q&A"
    url: "https://github.com/rustic-ai/prism/discussions/categories/q-a"
    about: "Ask questions about the AI development process or technical implementation"
  - name: "💡 Ideas & Suggestions"
    url: "https://github.com/rustic-ai/prism/discussions/categories/ideas"
    about: "Share creative ideas for the AI developer to consider"
  - name: "🎉 Show and Tell"
    url: "https://github.com/rustic-ai/prism/discussions/categories/show-and-tell"
    about: "Share how you're using Prism or cool discoveries you've made"
  - name: "📚 Documentation"
    url: "https://github.com/rustic-ai/prism/wiki"
    about: "Browse our comprehensive documentation and guides"
  - name: "🔒 Security Issues"
    url: "https://github.com/rustic-ai/prism/security/advisories/new"
    about: "Report security vulnerabilities privately (do not create public issues)"
  - name: "💬 General Discussion"
    url: "https://github.com/rustic-ai/prism/discussions/categories/general"
    about: "General discussion about AI-generated software development" 