# Basic MCP Server Test Configuration
# This configuration tests basic MCP protocol compliance

global:
  max_global_concurrency: 2
  timeout_seconds: 30
  fail_fast: false
  default_project_path: null

server:
  transport: "stdio"
  command: "node"
  args: ["server.js"]
  working_dir: null
  env:
    NODE_ENV: "test"
  url: null
  connection_timeout: 10
  startup_delay: 2

performance:
  enable_monitoring: true
  baseline_storage_path: "baselines/"
  regression_detection:
    warning_threshold_percent: 25.0
    error_threshold_percent: 50.0

test_suites:
  - name: "MCP Protocol Compliance"
    description: "Basic Model Context Protocol compliance tests"
    test_cases:
      - id: "initialize"
        tool_name: "initialize"
        description: "Test MCP initialization handshake"
        enabled: true
        input_params:
          protocolVersion: "2024-11-05"
          capabilities: {}
          clientInfo:
            name: "mcp-test-harness"
            version: "0.1.0"
        expected:
          patterns:
            - key: "protocolVersion"
              validation:
                type: "exists"
              required: true
            - key: "capabilities"
              validation:
                type: "exists"
              required: true
            - key: "serverInfo"
              validation:
                type: "exists"
              required: true
          allow_empty_results: false
          allow_failure: false
          performance_requirements:
            max_execution_time_ms: 5000
            max_memory_usage_mb: 64

      - id: "list_tools"
        tool_name: "tools/list"
        description: "List available tools"
        enabled: true
        input_params: null
        expected:
          patterns:
            - key: "tools"
              validation:
                type: "array"
              required: true
          allow_empty_results: true
          allow_failure: false
          performance_requirements:
            max_execution_time_ms: 3000
            max_memory_usage_mb: 32

      - id: "list_resources"
        tool_name: "resources/list"
        description: "List available resources"
        enabled: true
        input_params: null
        expected:
          patterns:
            - key: "resources"
              validation:
                type: "array"
              required: true
          allow_empty_results: true
          allow_failure: false
          performance_requirements:
            max_execution_time_ms: 3000
            max_memory_usage_mb: 32

baselines: null
